name: ${project.name}
version: ${project.version}

main: me.remag501.armor.ArmorPlugin
api-version: 1.21

commands:
  customarmorsets:
    description: Custom armor sets command.
    usage: /<command> give <set>

depend:
  - BGSCore
  - MythicMobs
  - LibsDisguises
  - Citizens