name: CustomArmorSets
version: 1.0
main: me.remag501.customarmorsets.CustomArmorSets
api-version: 1.21

commands:
  customarmorsets:
    description: Custom armor sets command.
    usage: /<command> give <set>

depend:
  - BGSCore
  - MythicMobs
  - LibsDisguises